#!/usr/bin/env bash

set -o errexit

voltcli="$(which voltdb 2>/dev/null)"
if [ -z "$voltcli" ]; then
    echo "The 'voltdb' program does not exist in your path."
    echo "Please ensure VoltDB is installed, and its bin"
    echo "directory has been added to your PATH setting."
    exit 1
fi

voltbin="$(dirname $voltcli)"

if [ ! -f $voltbin/dbenv ]; then
    echo "The expected 'dbenv' program is not present in"
    echo "the directory $voltbin."
    echo "Please check that VoltDB is correctly installed."
    exit 1
fi

source $voltbin/dbenv


