<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.voltdb</groupId>
        <artifactId>examples</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>compound-proc</artifactId>
    <packaging>jar</packaging>

    <name>VoltDB Examples : Compound Procedures</name>
    <description>
        Example code : Compound Procedures
    </description>

    <dependencies>
        <dependency>
            <groupId>org.voltdb</groupId>
            <artifactId>voltdbclient</artifactId>
            <version>${volt.client.version}</version>
        </dependency>

        <dependency>
            <groupId>org.voltdb</groupId>
            <artifactId>volt-procedure-api</artifactId>
            <version>${volt.procedure.api.version}</version>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src</sourceDirectory>
    </build>
</project>
