#!/bin/bash
# ============================================================================
# Generate Dockerfiles for ALL VoltDB Example Applications
# ============================================================================
# This script generates Dockerfiles for all 15 apps using a unified template
# NOTE: fraud-detection is excluded as it requires Apache Kafka
# with configuration for special cases (standalone POMs, data dirs, etc.)
#
# Usage:
#   ./generate-dockerfiles.sh           # Generate missing Dockerfiles
#   ./generate-dockerfiles.sh --force   # Regenerate all Dockerfiles
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

FORCE=false
if [ "$1" = "--force" ]; then
    FORCE=true
fi

# VoltDB image can be overridden via environment variable
VOLTDB_IMAGE="${VOLTDB_IMAGE:-voltactivedata/volt-developer-edition:15.2.0_voltdb}"

# ============================================================================
# Application Configurations
# ============================================================================
# Format: app_name|main_class|ddl_path|jar_type|has_data|data_path|standalone_pom|extra_envs
#
# jar_type:
#   - single: One JAR used for both procs and client (most apps)
#   - shaded: Separate shaded client JAR (voter)
#   - no_procs: No procs JAR, DDL has inline procedures (voltkv)
#
# has_data: yes/no - whether to copy data directory
# data_path: Path to data (empty = data/, or specific file like advertisers.csv)
# standalone_pom: yes/no - whether app has its own POM (not parent module)
# extra_envs: Comma-separated KEY=VALUE pairs for app-specific env vars
#   Common extra_envs:
#   - ARG_STYLE=positional: For apps using positional args (ddos-detection, fraud-tx-detection, simple)
#   - TARGET_TPS=N: Target transactions per second for positional arg apps
#   - CSV_LOADS="table:file": Load CSV data after DDL (metrocard loads station data)
#   - EXTRA_ARGS="...": Additional arguments passed to benchmark client
# ============================================================================

APPS="
voter|voter.client.AsyncBenchmark|src/main/resources/ddl.sql|single|no||no|CONTESTANTS=6,MAX_VOTES=2,EXTRA_ARGS=\"--contestants=6 --maxvotes=2\"
voltkv|voltkv.AsyncBenchmark|ddl.sql|no_procs|no||no|POOL_SIZE=100000,GET_PUT_RATIO=0.90,EXTRA_ARGS=\"--poolsize=100000 --getputratio=0.90\"
bank-offers|bankoffers.OfferBenchmark|ddl.sql|single|yes|data/|no|
metrocard|metrocard.MetroBenchmark|ddl.sql|single|yes|data/|no|CSV_LOADS=\"mc_stations:data/stations.csv\"
ddos-detection|com.example.voltdb.DdosDetectionApp|src/main/resources/ddl.sql|single|no||yes|ARG_STYLE=positional
fraud-tx-detection|com.example.voltdb.FraudDetectionApp|src/main/resources/ddl.sql|single|no||yes|ARG_STYLE=positional,TARGET_TPS=1000
adperformance|adperformance.AdTrackingBenchmark|ddl.sql|single|no||no|
callcenter|callcenter.CallCenterApp|ddl.sql|single|no||no|
geospatial|geospatial.AdBrokerBenchmark|ddl.sql|single|no|advertisers.csv|no|
json-sessions|jsonsessions.JSONClient|ddl.sql|single|no||no|
nbbo|nbbo.NbboBenchmark|ddl.sql|single|yes|data/|no|
positionkeeper|positionkeeper.PositionsBenchmark|ddl.sql|single|no||no|
simple|simple.Benchmark|ddl.sql|single|no||no|ARG_STYLE=positional,TARGET_TPS=50000
uniquedevices|uniquedevices.UniqueDevicesClient|ddl.sql|single|no||no|
windowing|windowing.WindowingApp|ddl.sql|single|no||no|
"

generate_dockerfile() {
    local app_name="$1"
    local main_class="$2"
    local ddl_path="$3"
    local jar_type="$4"
    local has_data="$5"
    local data_path="$6"
    local standalone_pom="$7"
    local extra_envs="$8"

    local dockerfile="$REPO_ROOT/$app_name/Dockerfile"

    if [ "$FORCE" = "false" ] && [ -f "$dockerfile" ]; then
        echo "Dockerfile already exists for $app_name, skipping (use --force to regenerate)"
        return
    fi

    echo "Generating Dockerfile for $app_name..."

    # Build the Dockerfile content
    cat > "$dockerfile" << 'EOF'
# ============================================================================
EOF

    cat >> "$dockerfile" << EOF
# VoltDB ${app_name} Example - Docker Image
# ============================================================================
# Auto-generated by generate-dockerfiles.sh - DO NOT EDIT MANUALLY
# To customize, edit the generator script and run with --force
#
# Build from repo root:
#   docker build -t voltdb-example-${app_name} -f ${app_name}/Dockerfile .
# ============================================================================

ARG VOLTDB_IMAGE=${VOLTDB_IMAGE}

# ----------------------------------------------------------------------------
# Stage 1: Build with Maven
# ----------------------------------------------------------------------------
FROM registry.access.redhat.com/ubi10-minimal:latest AS builder

# Install Java 21 and Maven dependencies
RUN microdnf upgrade --refresh --assumeyes --best && \\
    microdnf install --assumeyes --best --nodocs \\
      java-21-openjdk-devel \\
      tar \\
      gzip \\
      which && \\
    microdnf clean all

# Install Maven manually (not in UBI repos)
ARG MAVEN_VERSION=3.9.6
RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/\${MAVEN_VERSION}/binaries/apache-maven-\${MAVEN_VERSION}-bin.tar.gz | \\
    tar -xzf - -C /opt && \\
    ln -s /opt/apache-maven-\${MAVEN_VERSION} /opt/maven

ENV MAVEN_HOME=/opt/maven
ENV PATH="\${MAVEN_HOME}/bin:\${PATH}"
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk

WORKDIR /build

EOF

    # Add build commands based on standalone_pom
    if [ "$standalone_pom" = "yes" ]; then
        cat >> "$dockerfile" << EOF
# Standalone POM - copy only this module
COPY ${app_name}/pom.xml ./pom.xml
COPY ${app_name}/src ./src
COPY docker/scripts/entrypoint.sh ./entrypoint.sh

RUN mvn package -DskipTests -q && \\
    mvn dependency:copy-dependencies -DoutputDirectory=target/lib -DincludeScope=runtime -q

EOF
    else
        cat >> "$dockerfile" << EOF
# Copy entire project (needed for parent POM module resolution)
COPY . .

# Build and copy dependencies
RUN mvn package -pl ${app_name} -am -DskipTests -q && \\
    mkdir -p /build/${app_name}/target/dependency && \\
    mvn dependency:copy-dependencies -f ${app_name}/pom.xml \\
        -DoutputDirectory=/build/${app_name}/target/dependency \\
        -DincludeScope=runtime -q

EOF
    fi

    # Runtime stage
    cat >> "$dockerfile" << 'EOF'
# ----------------------------------------------------------------------------
# Stage 2: VoltDB source (for sqlcmd and tools)
# ----------------------------------------------------------------------------
FROM ${VOLTDB_IMAGE} AS voltdb-source

# ----------------------------------------------------------------------------
# Stage 3: Runtime Image
# ----------------------------------------------------------------------------
FROM registry.access.redhat.com/ubi10-minimal:latest

# Install runtime packages (minimal set for entrypoint.sh)
RUN microdnf install --assumeyes --best --nodocs \
      java-21-openjdk-headless \
      nc \
      shadow-utils \
      tar \
      which && \
    microdnf clean all

ENV JAVA_HOME=/usr/lib/jvm/jre-21-openjdk

# Copy VoltDB installation for sqlcmd and tools
COPY --from=voltdb-source /opt/voltdb /opt/voltdb

ENV VOLTDB_HOME=/opt/voltdb
ENV PATH="${VOLTDB_HOME}/bin:${JAVA_HOME}/bin:${PATH}"

WORKDIR /app

# Create non-root user
RUN groupadd -g 10000 voltapp && useradd -u 10000 -g voltapp -m voltapp

EOF

    # Add COPY commands based on jar_type and standalone_pom
    if [ "$standalone_pom" = "yes" ]; then
        # Standalone POM apps have different paths
        cat >> "$dockerfile" << EOF
# Copy artifacts from builder
COPY --from=builder /build/target/${app_name}-*.jar /app/app.jar
COPY --from=builder /build/target/lib/ /app/lib/
COPY --from=builder /build/src/main/resources/ddl.sql /app/ddl.sql
COPY --from=builder /build/entrypoint.sh /app/entrypoint.sh

# Rename for consistency
RUN mv /app/app.jar /app/client.jar && \\
    cp /app/client.jar /app/procs.jar && \\
    chmod +x /app/entrypoint.sh && \\
    chown -R voltapp:voltapp /app

EOF
    elif [ "$jar_type" = "shaded" ]; then
        # Voter-style with separate procs and shaded client JARs
        cat >> "$dockerfile" << EOF
# Copy artifacts from builder (shaded client JAR with all deps)
COPY --from=builder /build/${app_name}/target/${app_name}-procs.jar /app/procs.jar
COPY --from=builder /build/${app_name}/target/${app_name}-client.jar /app/client.jar
COPY --from=builder /build/${app_name}/${ddl_path} /app/ddl.sql
EOF
    elif [ "$jar_type" = "no_procs" ]; then
        # VoltKV-style with no procs JAR (inline procedures in DDL)
        cat >> "$dockerfile" << EOF
# Copy artifacts from builder (no procs JAR - DDL has inline procedures)
COPY --from=builder /build/${app_name}/target/${app_name}-1.0-SNAPSHOT.jar /app/client.jar
COPY --from=builder /build/${app_name}/target/dependency/ /app/lib/
COPY --from=builder /build/${app_name}/${ddl_path} /app/ddl.sql
EOF
    else
        # Standard single JAR for both procs and client
        cat >> "$dockerfile" << EOF
# Copy artifacts from builder
COPY --from=builder /build/${app_name}/target/${app_name}-1.0-SNAPSHOT.jar /app/procs.jar
COPY --from=builder /build/${app_name}/target/${app_name}-1.0-SNAPSHOT.jar /app/client.jar
COPY --from=builder /build/${app_name}/target/dependency/ /app/lib/
COPY --from=builder /build/${app_name}/${ddl_path} /app/ddl.sql
EOF
    fi

    # Add data copy if needed
    if [ "$has_data" = "yes" ] || [ -n "$data_path" ]; then
        if [ "$data_path" = "data/" ]; then
            cat >> "$dockerfile" << EOF

# Copy data directory
COPY --from=builder /build/${app_name}/data/ /app/data/
EOF
        elif [ -n "$data_path" ]; then
            cat >> "$dockerfile" << EOF

# Copy data file
COPY --from=builder /build/${app_name}/${data_path} /app/${data_path}
EOF
        fi
    fi

    # Add entrypoint copy and permissions (only for non-standalone apps)
    if [ "$standalone_pom" != "yes" ]; then
        cat >> "$dockerfile" << EOF

COPY docker/scripts/entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh && chown -R voltapp:voltapp /app

EOF
    fi

    # Add environment variables
    cat >> "$dockerfile" << EOF
ENV APP_NAME=${app_name}
ENV MAIN_CLASS=${main_class}
ENV DDL_FILE=/app/ddl.sql
EOF

    # Handle procs JAR env var
    if [ "$jar_type" = "no_procs" ]; then
        cat >> "$dockerfile" << 'EOF'
# No procs JAR - DDL has inline procedures
ENV PROCS_JAR=
EOF
    else
        cat >> "$dockerfile" << 'EOF'
ENV PROCS_JAR=/app/procs.jar
EOF
    fi

    cat >> "$dockerfile" << 'EOF'
ENV CLIENT_JAR=/app/client.jar
ENV VOLTDB_SERVERS=localhost:21212
ENV DURATION=120
ENV WARMUP=5
ENV DISPLAY_INTERVAL=5
ENV MODE=init-run
EOF

    # Add extra environment variables if specified
    if [ -n "$extra_envs" ]; then
        echo "" >> "$dockerfile"
        echo "# App-specific configuration" >> "$dockerfile"
        # Parse comma-separated env vars
        IFS=',' read -ra ENVS <<< "$extra_envs"
        for env in "${ENVS[@]}"; do
            echo "ENV $env" >> "$dockerfile"
        done
    fi

    # Add final USER and ENTRYPOINT
    cat >> "$dockerfile" << 'EOF'

USER voltapp
ENTRYPOINT ["/app/entrypoint.sh"]
EOF

    echo "Generated $dockerfile"
}

main() {
    echo "=============================================="
    echo "Generating Dockerfiles for VoltDB examples"
    echo "=============================================="
    if [ "$FORCE" = "true" ]; then
        echo "Mode: FORCE (regenerating all)"
    else
        echo "Mode: Skip existing (use --force to regenerate)"
    fi
    echo ""

    local count=0

    echo "$APPS" | while IFS='|' read -r app_name main_class ddl_path jar_type has_data data_path standalone_pom extra_envs; do
        # Skip empty lines
        [ -z "$app_name" ] && continue

        generate_dockerfile "$app_name" "$main_class" "$ddl_path" "$jar_type" "$has_data" "$data_path" "$standalone_pom" "$extra_envs"
        count=$((count + 1))
    done

    echo ""
    echo "=============================================="
    echo "Done! Dockerfile generation complete."
    echo "=============================================="
    echo ""
    echo "To build all images, run:"
    echo "  cd $REPO_ROOT/docker"
    echo "  make build-all"
}

main "$@"
